#!/usr/bin/env node
var net = require('net');
var socks = require('node-socks/socks.js');
var http = require('http');
var request = require('request');
var b64 = require('./lib/base64stream');

var tunnel_address, tunnel_port;

if (!process.argv[2]) {
  console.log('Usage: ./client TUNNEL_ADDRESS [MODE] # TUNNEL ADDRESS is the address of the tunnelling server. pass development as MODE for port 3001 ');
  return 0;
} else {
  tunnel_address = process.argv[2]
}

if (process.argv[3] == 'development') {
  tunnel_port = 3001;
} else {
  tunnel_port = 80;
}

// Create SOCKS server
// The server accepts SOCKS connections. This particular server acts as a proxy.
var HOST='127.0.0.1',
    PORT='8888'

var server = socks.createServer(function(socket, port, address, proxy_ready) {
  try {
    // Received a connection.
    var target_params = {address: address, port: port};
    var pretend_url = 'http://'+tunnel_address+':'+tunnel_port+'/'+(new Buffer(JSON.stringify(target_params))).toString('base64');
    console.log('Making a post to '+pretend_url);

    // Send the tunnel headers
    remote = request.put(pretend_url)
    remote.write(' '); // request makes the request when the first data is sent! ' ' in base64 is nothing.

    // Now pipe the data
    process.stdin.pipe(new b64.Encoder()).pipe(remote).pipe(new b64.Decoder()).pipe(process.stdout);

    proxy_ready(); // TODO - delay until the proxy is actually ready
  } catch(err) {
    console.log(err);
  }
});


server.listen(PORT, HOST);

// vim: set filetype=javascript syntax=javascript :

