#!/usr/bin/env node
var net = require('net');
var socks = require('node-socks/socks.js');
var http = require('http');
var request = require('request');

var tunnel_address;

if (!process.argv[2]) {
  console.log('Usage: ./client TUNNEL_ADDRESS # TUNNEL ADDRESS is the address of the tunnelling server');
  return 0;
} else {
  tunnel_address = process.argv[2]
}

// Create SOCKS server
// The server accepts SOCKS connections. This particular server acts as a proxy.
var HOST='127.0.0.1',
    PORT='8888'

var server = socks.createServer(function(socket, port, address, proxy_ready) {

  // Received a connection.
  var target_params = {address: address, port: port};
  var pretend_url = 'http://'+tunnel_address+':3001/'+(new Buffer(JSON.stringify(target_params))).toString('base64');
  console.log('Making a post to '+pretend_url);
  socket.pipe(request.post(pretend_url)).pipe(socket);
  proxy_ready(); // TODO - delay until the proxy is actually ready
});


server.listen(PORT, HOST);

// vim: set filetype=javascript syntax=javascript :

