#!/usr/bin/env node
var net = require('net');
var socks = require('node-socks/socks.js');
var http = require('http');
var request = require('request');
var strs = require('stringstream');
var b64 = require('./lib/base64stream');

var tunnel_address, tunnel_port;

if (!process.argv[2]) {
  console.log('Usage: ./ssh-connect TUNNEL_ADDRESS TARGET_ADDRESS TARGET_PORT [MODE] # TUNNEL ADDRESS is the address of the tunnelling server. pass development as MODE for port 3001 ');
  return 0;
} else {
  tunnel_address = process.argv[2]
}

if (process.argv[5] == 'development') {
  tunnel_port = 3001;
} else {
  tunnel_port = 80;
}


var target_params = {address: process.argv[3], port: process.argv[4]};
var pretend_url = 'http://'+tunnel_address+':'+tunnel_port+'/'+(new Buffer(JSON.stringify(target_params))).toString('base64');

process.stdin.resume(); // ?

remote = request.put(pretend_url)
remote.write(' '); // request makes the request when the first data is sent! ' ' in base64 is nothing.

process.stdin.pipe(new b64.Encoder()).pipe(remote).pipe(new b64.Decoder()).pipe(process.stdout);


// vim: set filetype=javascript syntax=javascript :

